apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
  namespace: go-server-namespace
  annotations:
    monitoring: "true"
spec:
  replicas: 2
  selector:
     matchLabels:
       app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - image: esc15/go-server:dev
        name: go-server
        ports:
        - containerPort: 8080
        resources:
          limits: 
            memory: "4Gi"
            cpu: "4"
          requests:
            memory: "2Gi"
            cpu: "2"
          