apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server
  name: go-server
  namespace: go-server-namespace
spec:
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-server
  type: NodePort